name: build-all

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # pulls all history and tags for Lerna to detect what packages changed.
          token: ${{ secrets.GITHUB_TOKEN }} # this token is available by defaulHK
      # [pnpm/action-setup: Install pnpm package manager]( https://github.com/pnpm/action-setup )
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      # install
      - name: Install dependencies
        run: pnpm install
      - run: pnpm build # will run "lerna run build"
      - run: pnpm test # will run "lerna run build"
      # publish
      - name: Configure Git User
        run: |
          git config --global user.email "snomiao@gmail.com"
          git config --global user.name "snomiao-ci@$GITHUB_ACTOR"
      - name: Check if able to publish changesk
        run: npm whoami # will throw and exit if npm is not ready to publish
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: lerna publish --yes
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Publish
      #   run: lerna publish from-git --yes
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: git commit -a -m "changes on ci" || echo nothing to commit
#       - name: Publish
#         run: lerna publish --yes --no-verify-access # the flag is needed if NPM_TOKEN is an Automation Token
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # set this token manually
#       # - run: npm run test # test only works in windows
#       # - run: npm run publish
#       #   env:
#       #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
