name: build-all

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # pulls all history and tags for Lerna to detect what packages changed.
          token: ${{ secrets.GITHUB_TOKEN }} # this token is available by defaulHK
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm build # will run "lerna run build"
      - run: pnpm test # will run "lerna run build"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Git User
        run: |
          git config --global user.email "snomiao@gmail.com"
          git config --global user.name "snomiao-ci@$GITHUB_ACTOR"
      - name: Publish
        run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       # - name: Check if able to publish changesk
#       #   run: npm whoami # will throw and exit if npm is not ready to publish
#       - run: git commit -a -m "changes on ci" || echo nothing to commit
#       - name: Publish
#         run: lerna publish --yes --no-verify-access # the flag is needed if NPM_TOKEN is an Automation Token
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # set this token manually
#       # - run: npm run test # test only works in windows
#       # - run: npm run publish
#       #   env:
#       #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
